{% set name = "conda-index" %}

package:
  name: {{ name|lower }}
  # VERSION_OVERRIDE is used by the canary release workflow
  version: {{ os.getenv("VERSION_OVERRIDE") or GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}

source:
  git_url: ../
  # url: https://github.com/conda/conda-index/archive/refs/tags/{{ version }}.tar.gz
  # sha256: ...

build:
  script: {{ PYTHON }} -m pip install --no-build-isolation . -vv
  number: 0
  noarch: python

requirements:
  host:
    - flit-core
    - python >=3.7
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >=3.7
    - click >=8
    - conda >=4.14.0
    - conda-package-streaming
    - filelock
    - jinja2
    - msgpack-python >=1.0.2
    - ruamel.yaml

test:
  requires:
    - conda-build >=24
    - conda-package-handling >=2.2.0
    - coverage
    - fsspec
    - pytest >=7
    - pytest-cov
    - pytest-mock
    - tomli
  commands:
    - pytest -k test_index_on_single_subdir_1
  imports:
    - conda_index.index
  source_files:
    - tests

about:
  home: https://github.com/conda/conda-index
  summary: Create `repodata.json` for collections of conda packages.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://conda.github.io/conda-index
  dev_url: https://github.com/conda/conda-index

extra:
  recipe-maintainers:
    - barabo
    - chenghlee
    - dholth
    - jezdez
