- name: Carl Anderson
  email: barabo@users.noreply.github.com
  num_commits: 1
  first_commit: 2022-07-26 09:56:39
  github: barabo
- name: Andrew Vallette
  email: andrewvallette@gmail.com
  num_commits: 1
  first_commit: 2022-06-28 20:09:54
  github: AndrewValette
- name: Daniel Holth
  email: dholth@anaconda.com
  num_commits: 92
  first_commit: 2022-05-18 19:49:18
  github: dholth
- name: jaimergp
  email: jaimergp@users.noreply.github.com
  num_commits: 2
  first_commit: 2023-08-29 10:56:37
  github: jaimergp
- name: Conda Bot
  email: conda-bot@users.noreply.github.com
  num_commits: 1
  first_commit: 2022-11-15 10:37:42
  github: conda-bot
  aliases:
  - 18747875+conda-bot@users.noreply.github.com
- name: Jannis Leidel
  email: jannis@leidel.info
  num_commits: 11
  first_commit: 2022-05-17 13:35:54
  github: jezdez
- name: conda-bot
  email: 18747875+conda-bot@users.noreply.github.com
  num_commits: 33
  first_commit: 2023-02-23 19:13:51
  github: conda-bot
- name: Ken Odegard
  email: kodegard@anaconda.com
  num_commits: 1
  first_commit: 2024-08-14 18:14:55
- name: Klaus Zimmermann
  email: klaus.zimmermann@quansight.com
  num_commits: 1
  first_commit: 2024-06-11 12:01:31
- name: Ryan Keith
  email: rkeith@anaconda.com
  github: ryanskeith
- name: Jay Roebuck
  email: jroebuck@esri.com
  github: jtroe
