name: Periodic Canary Build

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "17 14 * * WED"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux:
    # - this is a fork and manually-triggered, or
    # - this is the main repo, and
    # - we are on the main (or feature) branch
    if: >-
      (
        github.event.repository.fork
        && github.event_name == 'workflow_dispatch'
      )
      || (
        !github.event.repository.fork
        && (
          github.ref_name == 'main'
          || startsWith(github.ref_name, 'feature/')
        )
      )

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-canary/label/dev
          activate-environment: test_env
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true

      - name: Source Scripts
        run: |
          # pip >=22 is required for pip install -e conda-index
          conda install -c conda-canary/label/dev conda-build "pip>=22"
          pip install -e .[test]
          conda info -a
          pytest

  analyze:
    name: Analyze test results
    needs: [linux]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v3

      - name: Upload combined test results
        # provides one downloadable archive of all .coverage/test-report.xml files
        # of all matrix runs for further analysis.
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ github.sha }}-all
          path: test-results-${{ github.sha }}-*
          retention-days: 90 # default: 90

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: ./test-results-${{ github.sha }}-**/test-report*.xml

      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
